version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    build:
      commands:
        - echo Build started on `date`
        - sam build
        - sam local invoke
    post_build:
      commands:
        - echo Build completed on `date`
        - pwd
        - ls -al
artifacts:
  files:
    - '**/*'
  name: bbdartifact