version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    build:
      commands:
        - echo Build started on `date`
        - USER_BASE_PATH=$(python -m site --user-base)
        - export PATH=$PATH:$USER_BASE_PATH/bin
        - sam build
    post_build:
      commands:
        - echo Build completed on `date`
        - sam package --output-template-file packaged.yaml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-10mxe3shgahk2
        - ls -al
artifacts:
  type: zip
  files:
    - CODEBUILD_SRC_DIR