version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    build:
      commands:
        - "mkdir .aws-sam"
        - "cd .aws/sam"
        - "touch file12.txt"
    post_build:
      commands:
        - "cd $CODEBUILD_SRC_DIR"
        - "ls -al"
artifacts:
  type: zip
  base-directory: "$CODEBUILD_SRC_DIR/.aws-sam/"
  files:
    - '**/*'