version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    build:
      commands:
        - "cd $CODEBUILD_SRC_DIR"
        - "sam build"
    post_build:
      commands:
        - "ls -al"
artifacts:
  type: zip
  files:
    - '$CODEBUILD_SRC_DIR/demo_lambda/*'