version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - "python setup.py install"
      - "cd demo_lambda"
      - "pip install -r requirements.txt"
      - "python -m unittest discover tests"
      - "cd .."
  build:
    commands:
      - "sam build"
  post_build:
    commands:
      - "sam package --output-template-file packaged.yaml --s3-bucket codebuild-deployment-bucket-l3ajvfole2"
      - "ls -al"
artifacts:
  type: zip
  files:
    - '**/*'