version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    build:
      commands:
        - "sam build"
    post_build:
      commands:
        - "ls -al"
artifacts:
  type: zip
  base-directory: $CODEBUILD_SRC_DIR
  files:
    - '**/*'