version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    build:
      commands:
        - echo Build started on `date`
        - sam build
    post_build:
      commands:
        - echo Build completed on `date`
        - sam package --output-template-file packaged.yaml
        - ls -al
artifacts:
  type: zip
  files:
    - packaged.yaml