version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - python -m unittest discover tests
  build:
    commands:
      - sam build
  post_build:
    commands:
      - ls -al
artifacts:
  type: zip
  base-directory: $CODEBUILD_SRC_DIR/.aws-sam/build/DemoLambda
  files:
    - '**/*'